name: DeathSecondChance
version: '0.1'
author: niqita
main: me.niqita.deathsecondchance.Main
permissions:
  purgatory.GOD: {}
commands:
  stop-when-purgatory-empty:
    permission: purgatory.GOD
  cancel-stopping:
    permission: purgatory.GOD
  set-purgatory:
    permission: purgatory.GOD
  free-player:
    permission: purgatory.GOD
  set-exit-purgatory:
    permission: purgatory.GOD

